// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbKRIMH0WcbFQiiVQf_clp0ynELT9OrqU',
    appId: '1:93656505089:web:7b6f2f75aa16e761a81900',
    messagingSenderId: '93656505089',
    projectId: 'fruithub0',
    authDomain: 'fruithub0.firebaseapp.com',
    storageBucket: 'fruithub0.firebasestorage.app',
    measurementId: 'G-EFZ9NMYY2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRyqGNsY9CuU3VLmVwF3AWUxyIwTJx_c',
    appId: '1:93656505089:android:bd710d69e1435390a81900',
    messagingSenderId: '93656505089',
    projectId: 'fruithub0',
    storageBucket: 'fruithub0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSoSX0u2Ifj7dcQQPSXQSqMW45HHKduoc',
    appId: '1:93656505089:ios:3e006d8bd8b6c3c1a81900',
    messagingSenderId: '93656505089',
    projectId: 'fruithub0',
    storageBucket: 'fruithub0.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSoSX0u2Ifj7dcQQPSXQSqMW45HHKduoc',
    appId: '1:93656505089:ios:3e006d8bd8b6c3c1a81900',
    messagingSenderId: '93656505089',
    projectId: 'fruithub0',
    storageBucket: 'fruithub0.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbKRIMH0WcbFQiiVQf_clp0ynELT9OrqU',
    appId: '1:93656505089:web:924caa29dfd10b7aa81900',
    messagingSenderId: '93656505089',
    projectId: 'fruithub0',
    authDomain: 'fruithub0.firebaseapp.com',
    storageBucket: 'fruithub0.firebasestorage.app',
    measurementId: 'G-T9M12VDV3D',
  );
}
